transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/ULA32bits.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/somador32bits.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/somador1bit.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/processador.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/or32bits.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/or1bit.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/mux8por1_32bits.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/mux8por1_1bit.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/mux2por1_5bits.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/mux2por1_32bits.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/mux2por1.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/memoriaInstrucao.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/hex_display.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/extensor_sinal.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/divisor_frequencia.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/decodificador_operacao_hex.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/countPC.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/bancoRegistradores.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/and32bits.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/and1bit.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/unidadeControleULA.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/unidadeControlePrincipal.v}
vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/pratica7_top.v}

vlog -vlog01compat -work work +incdir+C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle {C:/Users/gioes/Documents/GitHub-Projects/university-coursework/2025-2/computer-organization-and-architecture/pratica7_GiovanniEstevam_JoaoVitorLopes/unidadeControle/processador_tb.v}

vsim -t 1ps -L altera_ver -L lpm_ver -L sgate_ver -L altera_mf_ver -L altera_lnsim_ver -L cycloneii_ver -L rtl_work -L work -voptargs="+acc"  processador_tb

add wave *
view structure
view signals
run -all
